<?php

namespace AbonnementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AbonneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbonneRepository extends EntityRepository
{
}
